"""``<framework>-update-check`` CLI.

Runs as a systemd timer to poll for new releases of the shared framework
(scottycore by default, but brand-configurable). The prog name in --help
uses the current brand's framework name.

Typical systemd wiring (generated by ``deploy/install.sh``):

    [Unit]
    Description=<framework> update poller (%i)
    [Service]
    Type=oneshot
    WorkingDirectory=/opt/<framework>/%i
    ExecStart=/usr/local/bin/<framework>-update-check --repo-root /opt/<framework>/%i
    User=root
    Environment="DATABASE_URL=postgresql+asyncpg://..."
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path

from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from scottycore.core.brand import get_brand
from scottycore.services.auto_update.service import (
    AutoUpdateService,
    _default_forge_api,
)


def main(argv: list[str] | None = None) -> int:
    brand = get_brand()
    parser = argparse.ArgumentParser(
        prog=f"{brand.framework_name}-update-check",
        description=(
            f"Poll the {brand.framework_name} pin and notify/auto-update "
            "per settings."
        ),
    )
    parser.add_argument(
        "--repo-root",
        required=True,
        help="Path to the app repo (where pyproject.toml lives)",
    )
    parser.add_argument(
        "--forge-api",
        default=_default_forge_api(brand),
        help="Forge API base URL (github or forgejo-compatible)",
    )
    ns = parser.parse_args(argv)

    try:
        result = asyncio.run(_run(ns, brand))
    except KeyboardInterrupt:
        return 130
    print(json.dumps(result, default=str))
    if result["action_taken"] == "auto-updated":
        # Signal the host runner to rebuild. Exit 75 = "please restart me"
        # (Python's EX_TEMPFAIL convention, also used by the admin
        # restart endpoint).
        return 75
    if result["action_taken"] == "error":
        return 1
    return 0


async def _run(ns: argparse.Namespace, brand) -> dict:  # type: ignore[no-untyped-def]
    from scottycore.core.database import _build_engine

    engine = _build_engine()
    factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    svc = AutoUpdateService(
        repo_root=Path(ns.repo_root),
        session_factory=factory,
        forge_api=ns.forge_api,
        brand=brand,
    )
    result = await svc.check_once()
    await engine.dispose()
    return {
        "current_pin": result.current_pin,
        "latest_pin": result.latest_pin,
        "mode": result.mode,
        "action_taken": result.action_taken,
        "detail": result.detail,
    }


if __name__ == "__main__":
    sys.exit(main())
